In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
arr_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr_mul[1])
print(arr_mul[0,2])

print(arr_mul.shape)
print(arr_mul.ndim)
print(arr_mul.size)
print(arr_mul.dtype)

[4 5 6]
3
(3, 3)
2
9
int64


In [ ]:
full_arr = np.full((2,3,4), 9)
print(full_arr)

zero_arr = np.zeros((1,3,2))
print(zero_arr)

ones_arr = np.ones((1,3,3))
print(ones_arr)

# np.zeros x np.empty
empty_arr = np.empty((1,5,5))
print(empty_arr)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307
   1.42410974e-306]
  [1.95821439e-306 9.34613185e-307 2.04712907e-306 1.95818994e-306
   1.11261502e-306]
  [6.23059726e-307 9.45697982e-308 3.11525958e-307 1.69118108e-306
   8.06632139e-308]
  [1.20160711e-306 1.69119330e-306 1.29062229e-306 1.24610383e-306
   6.89804132e-307]
  [2.22522053e-306 1.11261095e-306 1.11260144e-306 8.34448533e-308
   3.91792476e-317]]]


In [22]:
x_values = np.arange(0, 100, 5)
print(x_values)

x_values = np.linspace(0,100,5)
print(x_values)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0.  25.  50.  75. 100.]


In [24]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)

print(l1 * 5)
print(a1 * 5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [28]:
a = np.array([[1,2,3],
             [4,5,6]])

print(np.sqrt(a))
print(np.sin(a))
print(np.tan(a))
print(np.log10(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [37]:
ar = np.array([1,2,3])
ar = np.append(ar, [7,8,9])
ar = np.insert(ar, 3, [4,5,6])

print(ar)

a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(np.delete(a, 2, 1))

[1 2 3 4 5 6 7 8 9]
[[1 2]
 [4 5]]
